### PR TITLE
Add support for vmull2, ngc xzr sbcs xzrs, sbcs xzrs and cmn

### PR DESCRIPTION
**Pull request by aqjune**
This adds support for a few arithmetic instructions in AArch64.

The updated uarchs are Neoverse N1 and Cortex A55.

### CODE REVIEW

**Review by hanno-becker — COMMENTED** [review]
Thank you @aqjune!

Do you mind updating the A55 model as well?

**Comment by hanno-becker** [comment]
> For other arithmetic ops - what would be a good step to check these?

I don't follow yet -- can you elaborate?

**Comment by aqjune** [comment]
> I don't follow yet -- can you elaborate?
I was wondering whether the subclass relation between `AArch*Instruction` and the new instructions could silently add cost models to microarchitectures other than Neoverse N1. I checked that it did not introduce that.

Also this PR is updated to support Cortex A55 now too.

**Comment by aqjune** [comment]
Oops, the committer and author are different. I will quickly amend it...

**Review by hanno-becker — APPROVED** [review]
LGTM, thanks June!

**Pull request merged**
